"""empty message

Revision ID: 63f00d7a2678
Revises: e17b1e74105f
Create Date: 2019-12-06 11:55:02.556873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f00d7a2678'
down_revision = 'e17b1e74105f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('airtime', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishers_airtime'), 'publishers', ['airtime'], unique=False)
    op.create_index(op.f('ix_publishers_comment'), 'publishers', ['comment'], unique=False)
    op.create_index(op.f('ix_publishers_created_at'), 'publishers', ['created_at'], unique=False)
    op.create_index(op.f('ix_publishers_name'), 'publishers', ['name'], unique=True)
    op.create_index(op.f('ix_publishers_updated_at'), 'publishers', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publishers_updated_at'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_name'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_created_at'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_comment'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_airtime'), table_name='publishers')
    op.drop_table('publishers')
    # ### end Alembic commands ###
