"""empty message

Revision ID: 76066ae2f2c7
Revises: e1cf5092ba4c
Create Date: 2020-02-27 14:04:36.579809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76066ae2f2c7'
down_revision = 'e1cf5092ba4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM files')
    op.add_column('files', sa.Column('publisher_id', sa.Integer(), nullable=False))
    op.add_column('files', sa.Column('status', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_files_publisher_id'), 'files', ['publisher_id'], unique=False)
    op.create_index(op.f('ix_files_status'), 'files', ['status'], unique=False)
    op.create_foreign_key(None, 'files', 'publishers', ['publisher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('files_publisher_id_fkey', 'files', type_='foreignkey')
    op.drop_index(op.f('ix_files_status'), table_name='files')
    op.drop_index(op.f('ix_files_publisher_id'), table_name='files')
    op.drop_column('files', 'status')
    op.drop_column('files', 'publisher_id')
    # ### end Alembic commands ###
