"""empty message

Revision ID: e1cf5092ba4c
Revises: fd2323e775c7
Create Date: 2020-02-27 08:08:07.446670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cf5092ba4c'
down_revision = 'fd2323e775c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('publisher_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_publisher_id'), 'users', ['publisher_id'], unique=False)
    op.create_foreign_key(None, 'users', 'publishers', ['publisher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_publisher_id_fkey', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_publisher_id'), table_name='users')
    op.drop_column('users', 'publisher_id')
    # ### end Alembic commands ###
