"""empty message

Revision ID: e4b8d054ca11
Revises: f3393551b301
Create Date: 2020-02-14 10:50:45.809415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b8d054ca11'
down_revision = 'f3393551b301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM devices_health')
    op.alter_column('devices_health', 'device_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='device_id::integer')
    op.create_foreign_key(None, 'devices_health', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('devices_health_device_id_fkey', 'devices_health', type_='foreignkey')
    op.alter_column('devices_health', 'device_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
