"""empty message

Revision ID: f3393551b301
Revises: 63f00d7a2678
Create Date: 2020-01-10 11:10:29.052059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3393551b301'
down_revision = '227581b2c6df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('software_version', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_health_created_at'), 'devices_health', ['created_at'], unique=False)
    op.create_index(op.f('ix_devices_health_device_id'), 'devices_health', ['device_id'], unique=False)
    op.create_index(op.f('ix_devices_health_software_version'), 'devices_health', ['software_version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_health_software_version'), table_name='devices_health')
    op.drop_index(op.f('ix_devices_health_device_id'), table_name='devices_health')
    op.drop_index(op.f('ix_devices_health_created_at'), table_name='devices_health')
    op.drop_table('devices_health')
    # ### end Alembic commands ###
