import {
  USERS_ROLE_ADMIN,
  USERS_ROLE_ADMIN_TITLE,
  USERS_ROLE_USER,
  USERS_ROLE_USER_TITLE,
  USERS_ROLE_MANAGER,
  USERS_ROLE_MANAGER_TITLE,
  USERS_STATUS_ACTIVE,
  USERS_STATUS_ACTIVE_TITLE,
  USERS_STATUS_DISABLED,
  USERS_STATUS_DISABLED_TITLE,
  USERS_STATUS_DELETED,
  USERS_STATUS_DELETED_TITLE,
  USERS_STATUS_ARCHIVE,
  USERS_STATUS_ARCHIVE_TITLE,
} from './consts';


export function getRoleTitle(name) {
  switch (name) {
    case USERS_ROLE_ADMIN:
      return USERS_ROLE_ADMIN_TITLE;
    case USERS_ROLE_USER:
      return USERS_ROLE_USER_TITLE;
    case USERS_ROLE_MANAGER:
      return USERS_ROLE_MANAGER_TITLE;
  }
}


export function getStatusTitle(name) {
  switch (name) {
    case USERS_STATUS_ACTIVE:
      return USERS_STATUS_ACTIVE_TITLE;
    case USERS_STATUS_DISABLED:
      return USERS_STATUS_DISABLED_TITLE;
    case USERS_STATUS_DELETED:
      return USERS_STATUS_DELETED_TITLE;
    case USERS_STATUS_ARCHIVE:
      return USERS_STATUS_ARCHIVE_TITLE;
  }
}
