import {
  USERS_ROLE_ADMIN,
  USERS_ROLE_ADMIN_TITLE,
  USERS_ROLE_MANAGER,
  USERS_ROLE_MANAGER_TITLE,
  USERS_ROLE_USER,
  USERS_ROLE_USER_TITLE
} from '../../consts';


export const roles = [
  { value: USERS_ROLE_USER, label: USERS_ROLE_USER_TITLE },
  { value: USERS_ROLE_MANAGER, label: USERS_ROLE_MANAGER_TITLE },
  { value: USERS_ROLE_ADMIN, label: USERS_ROLE_ADMIN_TITLE },
];
